//===- LowerToCuda.cpp - PolyKernel --lower-to-cuda pass --------*- C++ -*-===//
//
// PolyKernel out-of-tree MLIR dialect: the `--lower-to-cuda` source-emitter pass
// (Todo 8 / Wave 2).
//
//===----------------------------------------------------------------------===//
//
// EMISSION APPROACH (Pinned contract F). This pass is a CUSTOM SOURCE EMITTER,
// not an IR-to-IR lowering: it walks the PolyKernel IR, recognizes the compute
// op kinds present, and for each one STRING-EMITS a portable CUDA/HIP kernel
// source file (.cu) into --output-dir (default kernels/generated). It does NOT
// use the upstream gpu-to-llvm / convert-to-llvm pipelines. The emitted .cu is
// written against kernels/template/kernel_common.h, so the SAME file compiles
// unchanged under `nvcc -DPOLYKERNEL_CUDA` (Wave 2) and `hipcc -DPOLYKERNEL_HIP`
// (Wave 4); the nvcc driver (tools/polykernel-bench/nvcc_driver.py) then compiles
// it to PTX + ptxas stats.
//
// Todo 8 emits a PRE-WRITTEN, TEMPLATED kernel per recognized op kind: the
// RMSNorm kernel below is emitted verbatim (epsilon and weight-presence are
// runtime kernel parameters, so one emitted .cu handles any shape/epsilon). The
// deliverable is the emission PIPELINE — walk IR -> dispatch by op kind ->
// string-emit .cu text -> write file. Todo 9/10 grow the dispatch table with
// gelu/silu/matmul/softmax emitters and add real per-op shape/attr
// parameterization of the emitted text.
//
//===----------------------------------------------------------------------===//

#include "PolyKernel/Passes/LowerToCuda.h"

#include "PolyKernel/IR/PolyKernelOps.h"

#include "mlir/IR/BuiltinOps.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir::polykernel {
#define GEN_PASS_DEF_LOWERTOCUDA
#include "PolyKernel/Passes/Passes.h.inc"
} // namespace mlir::polykernel

using namespace mlir;

namespace mlir::polykernel {
namespace {

//===----------------------------------------------------------------------===//
// Per-op kernel emitters. Each writes a complete, self-contained .cu (kernel +
// host launch_* entry) to `os`. Todo 9 adds emitGeluCuda / emitSiluCuda; Todo 10
// adds emitMatMulCuda / emitSoftmaxCuda here and registers them in the dispatch.
//===----------------------------------------------------------------------===//

void emitRmsNormCuda(raw_ostream &os) {
  os << R"POLYKERNEL(//===- rmsnorm.cu - PolyKernel generated RMSNorm kernel ---------*- CUDA -*-===//
//
// AUTO-GENERATED by `polykernel-opt --lower-to-cuda` (Todo 8 / Wave 2).
// Do not edit by hand; re-run the pass to regenerate.
//
// RMSNorm over the last axis: y = x / sqrt(mean(x^2) + epsilon) [* weight].
// bf16 in/out, fp32 accumulation + reduction (matches tests/golden/golden.py).
// Written against the portable template (kernels/template/kernel_common.h) so it
// compiles UNCHANGED under `nvcc -DPOLYKERNEL_CUDA` and `hipcc -DPOLYKERNEL_HIP`.
//
//===----------------------------------------------------------------------===//

#include "../template/kernel_common.h"

namespace {

constexpr int kBlockThreads = 256;
constexpr int kNumWarps = kBlockThreads / PK_WARP_SIZE;

// Butterfly warp sum reduction; the result lands in every lane of the warp.
PK_DEVICE_INLINE float warp_reduce_sum(float v) {
#pragma unroll
  for (int offset = PK_WARP_SIZE / 2; offset > 0; offset >>= 1)
    v += pk_shfl_xor_sync(v, offset);
  return v;
}

// Block sum reduction: per-warp partials -> shared -> warp 0 finalizes. The
// total is returned in every lane of warp 0 (thread 0 in particular).
PK_DEVICE float block_reduce_sum(float v, float *warp_sums) {
  int lane = threadIdx.x & (PK_WARP_SIZE - 1);
  int warp = threadIdx.x / PK_WARP_SIZE;
  v = warp_reduce_sum(v);
  if (lane == 0)
    warp_sums[warp] = v;
  pk_syncthreads();
  v = (threadIdx.x < kNumWarps) ? warp_sums[lane] : 0.0f;
  if (warp == 0)
    v = warp_reduce_sum(v);
  return v;
}

// One block per row (last-axis reduction). Vectorized bf16x2 loads over the
// aligned even bulk + a scalar tail for an odd trailing element. The memcpy-based
// pk_load_bf16x2 is alignment-safe, so an odd `cols` (misaligned odd rows) is
// handled correctly.
PK_GLOBAL void rmsnorm_kernel(const pk_bf16 *__restrict__ input,
                              const pk_bf16 *__restrict__ weight,
                              pk_bf16 *__restrict__ output, int cols,
                              float epsilon, int has_weight) {
  PK_SHARED float warp_sums[kNumWarps];
  PK_SHARED float s_rms;

  const int row = blockIdx.x;
  const int tid = threadIdx.x;
  const pk_bf16 *xrow = input + static_cast<size_t>(row) * cols;
  pk_bf16 *yrow = output + static_cast<size_t>(row) * cols;

  // Pass 1: sum of squares in fp32 (bf16 input upcast exactly to fp32).
  float local_ss = 0.0f;
  const int cols2 = cols & ~1; // even bulk
  for (int i = tid * 2; i < cols2; i += kBlockThreads * 2) {
    pk_bf16x2 v = pk_load_bf16x2(xrow + i);
    float a = pk_bf162float(v.x);
    float b = pk_bf162float(v.y);
    local_ss += a * a + b * b;
  }
  if ((cols & 1) && tid == 0) {
    float a = pk_bf162float(xrow[cols - 1]);
    local_ss += a * a;
  }

  float ss = block_reduce_sum(local_ss, warp_sums);
  if (tid == 0)
    s_rms = sqrtf(ss / static_cast<float>(cols) + epsilon);
  pk_syncthreads();
  float rms = s_rms;

  // Pass 2: normalize, optional per-feature weight, round back to bf16, store.
  for (int i = tid * 2; i < cols2; i += kBlockThreads * 2) {
    pk_bf16x2 v = pk_load_bf16x2(xrow + i);
    float a = pk_bf162float(v.x) / rms;
    float b = pk_bf162float(v.y) / rms;
    if (has_weight) {
      pk_bf16x2 wv = pk_load_bf16x2(weight + i);
      a *= pk_bf162float(wv.x);
      b *= pk_bf162float(wv.y);
    }
    pk_store_bf16x2(yrow + i,
                    pk_make_bf16x2(pk_float2bf16(a), pk_float2bf16(b)));
  }
  if ((cols & 1) && tid == 0) {
    int i = cols - 1;
    float a = pk_bf162float(xrow[i]) / rms;
    if (has_weight)
      a *= pk_bf162float(weight[i]);
    yrow[i] = pk_float2bf16(a);
  }
}

} // namespace

// Host-callable launch entry (the launch_*-style ABI). The stream is passed as
// void* to keep the signature backend-agnostic and cast to the backend stream
// type (pk_stream_t) inside.
void launch_rmsnorm(const pk_bf16 *input, const pk_bf16 *weight,
                    pk_bf16 *output, int rows, int cols, float epsilon,
                    void *stream) {
  int has_weight = (weight != nullptr) ? 1 : 0;
  pk_stream_t s = static_cast<pk_stream_t>(stream);
  PK_LAUNCH(rmsnorm_kernel, dim3(rows), dim3(kBlockThreads), 0, s, input, weight,
            output, cols, epsilon, has_weight);
  PK_CHECK(pk_get_last_error());
}
)POLYKERNEL";
}

void emitGeluCuda(raw_ostream &os) {
  os << R"POLYKERNEL(//===- gelu.cu - PolyKernel generated GELU kernel ---------------*- CUDA -*-===//
//
// AUTO-GENERATED by `polykernel-opt --lower-to-cuda` (Todo 9 / Wave 2).
// Do not edit by hand; re-run the pass to regenerate.
//
// Exact erf-based GELU (matches tests/golden/golden.py):
//     y = 0.5 * x * (1 + erf(x / sqrt(2))).
// bf16 in/out, fp32 compute (matches the golden rounding contract). Written
// against the portable template (kernels/template/kernel_common.h) so it compiles
// UNCHANGED under `nvcc -DPOLYKERNEL_CUDA` and `hipcc -DPOLYKERNEL_HIP` (erff is
// device math on both; everything else is behind pk_* / PK_* macros).
//
//===----------------------------------------------------------------------===//

#include "../template/kernel_common.h"

namespace {

constexpr int kBlockThreads = 256;
constexpr int kMaxBlocks = 65535;
constexpr float kInvSqrt2 = 0.70710678118654752440f; // 1 / sqrt(2)

PK_DEVICE_INLINE float gelu_one(float x) {
  return 0.5f * x * (1.0f + erff(x * kInvSqrt2));
}

// Flat elementwise GELU over `n` elements. Vectorized bf16x2 over the aligned
// even bulk + a scalar tail for an odd trailing element (the memcpy-based
// pk_load_bf16x2 is alignment-safe, so an odd `n` is handled correctly).
PK_GLOBAL void gelu_kernel(const pk_bf16 *__restrict__ input,
                           pk_bf16 *__restrict__ output, int n) {
  const int tid = blockIdx.x * blockDim.x + threadIdx.x;
  const int stride = gridDim.x * blockDim.x;
  const int n2 = n & ~1; // even bulk
  for (int i = tid * 2; i < n2; i += stride * 2) {
    pk_bf16x2 v = pk_load_bf16x2(input + i);
    float a = gelu_one(pk_bf162float(v.x));
    float b = gelu_one(pk_bf162float(v.y));
    pk_store_bf16x2(output + i,
                    pk_make_bf16x2(pk_float2bf16(a), pk_float2bf16(b)));
  }
  if ((n & 1) && tid == 0)
    output[n - 1] = pk_float2bf16(gelu_one(pk_bf162float(input[n - 1])));
}

} // namespace

// Host-callable launch entry (the launch_*-style ABI). The stream is passed as
// void* to keep the signature backend-agnostic and cast to the backend stream
// type (pk_stream_t) inside.
void launch_gelu(const pk_bf16 *input, pk_bf16 *output, int n, void *stream) {
  int pairs = n / 2;
  int blocks = (pairs + kBlockThreads - 1) / kBlockThreads;
  if (blocks < 1)
    blocks = 1;
  if (blocks > kMaxBlocks)
    blocks = kMaxBlocks;
  pk_stream_t s = static_cast<pk_stream_t>(stream);
  PK_LAUNCH(gelu_kernel, dim3(blocks), dim3(kBlockThreads), 0, s, input, output,
            n);
  PK_CHECK(pk_get_last_error());
}
)POLYKERNEL";
}

void emitSiluCuda(raw_ostream &os) {
  os << R"POLYKERNEL(//===- silu.cu - PolyKernel generated SiLU kernel ---------------*- CUDA -*-===//
//
// AUTO-GENERATED by `polykernel-opt --lower-to-cuda` (Todo 9 / Wave 2).
// Do not edit by hand; re-run the pass to regenerate.
//
// SiLU / swish (matches tests/golden/golden.py):
//     y = x / (1 + exp(-x)).
// bf16 in/out, fp32 compute (matches the golden rounding contract). Written
// against the portable template (kernels/template/kernel_common.h) so it compiles
// UNCHANGED under `nvcc -DPOLYKERNEL_CUDA` and `hipcc -DPOLYKERNEL_HIP` (expf is
// device math on both; everything else is behind pk_* / PK_* macros).
//
//===----------------------------------------------------------------------===//

#include "../template/kernel_common.h"

namespace {

constexpr int kBlockThreads = 256;
constexpr int kMaxBlocks = 65535;

PK_DEVICE_INLINE float silu_one(float x) { return x / (1.0f + expf(-x)); }

// Flat elementwise SiLU over `n` elements. Vectorized bf16x2 over the aligned
// even bulk + a scalar tail for an odd trailing element (the memcpy-based
// pk_load_bf16x2 is alignment-safe, so an odd `n` is handled correctly).
PK_GLOBAL void silu_kernel(const pk_bf16 *__restrict__ input,
                           pk_bf16 *__restrict__ output, int n) {
  const int tid = blockIdx.x * blockDim.x + threadIdx.x;
  const int stride = gridDim.x * blockDim.x;
  const int n2 = n & ~1; // even bulk
  for (int i = tid * 2; i < n2; i += stride * 2) {
    pk_bf16x2 v = pk_load_bf16x2(input + i);
    float a = silu_one(pk_bf162float(v.x));
    float b = silu_one(pk_bf162float(v.y));
    pk_store_bf16x2(output + i,
                    pk_make_bf16x2(pk_float2bf16(a), pk_float2bf16(b)));
  }
  if ((n & 1) && tid == 0)
    output[n - 1] = pk_float2bf16(silu_one(pk_bf162float(input[n - 1])));
}

} // namespace

// Host-callable launch entry (the launch_*-style ABI). The stream is passed as
// void* to keep the signature backend-agnostic and cast to the backend stream
// type (pk_stream_t) inside.
void launch_silu(const pk_bf16 *input, pk_bf16 *output, int n, void *stream) {
  int pairs = n / 2;
  int blocks = (pairs + kBlockThreads - 1) / kBlockThreads;
  if (blocks < 1)
    blocks = 1;
  if (blocks > kMaxBlocks)
    blocks = kMaxBlocks;
  pk_stream_t s = static_cast<pk_stream_t>(stream);
  PK_LAUNCH(silu_kernel, dim3(blocks), dim3(kBlockThreads), 0, s, input, output,
            n);
  PK_CHECK(pk_get_last_error());
}
)POLYKERNEL";
}

//===----------------------------------------------------------------------===//
// The pass.
//===----------------------------------------------------------------------===//

class LowerToCudaPass : public impl::LowerToCudaBase<LowerToCudaPass> {
public:
  void runOnOperation() override {
    ModuleOp module = getOperation();

    // Detect which op kinds are present (deduplicated): one .cu per kind.
    bool hasRmsNorm = false;
    bool hasGelu = false;
    bool hasSilu = false;
    // Todo 10: bool hasMatMul, hasSoftmax, ...
    module.walk([&](Operation *op) {
      if (isa<RmsNormOp>(op))
        hasRmsNorm = true;
      else if (isa<GeluOp>(op))
        hasGelu = true;
      else if (isa<SiluOp>(op))
        hasSilu = true;
      // Todo 10: else if (isa<MatMulOp>(op)) hasMatMul = true; ...
    });

    if (hasRmsNorm && failed(emitKernelFile("rmsnorm.cu", emitRmsNormCuda)))
      return signalPassFailure();
    if (hasGelu && failed(emitKernelFile("gelu.cu", emitGeluCuda)))
      return signalPassFailure();
    if (hasSilu && failed(emitKernelFile("silu.cu", emitSiluCuda)))
      return signalPassFailure();
    // Todo 10: emit matmul.cu / softmax.cu here.

    // The IR is intentionally left unchanged (source emitter, not a transform).
  }

private:
  /// Create --output-dir if needed and write one emitted kernel file into it.
  LogicalResult emitKernelFile(StringRef filename,
                               void (*emitter)(raw_ostream &)) {
    if (std::error_code ec = llvm::sys::fs::create_directories(outputDir)) {
      getOperation().emitError("cannot create output directory '")
          << outputDir << "': " << ec.message();
      return failure();
    }
    llvm::SmallString<128> path(outputDir);
    llvm::sys::path::append(path, filename);

    std::error_code ec;
    llvm::raw_fd_ostream out(path, ec, llvm::sys::fs::OF_Text);
    if (ec) {
      getOperation().emitError("cannot open '") << path << "': " << ec.message();
      return failure();
    }
    emitter(out);
    out.flush();
    return success();
  }
};

} // namespace

std::unique_ptr<Pass> createLowerToCudaPass() {
  return std::make_unique<LowerToCudaPass>();
}

} // namespace mlir::polykernel
